# Generated by Django 5.1.4 on 2024-12-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoteca', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciente',
            name='item',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='item',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='reciente',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='favorito',
            name='discoteca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discoteca.discoteca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciente',
            name='discoteca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discoteca.discoteca'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
